var resources = {
    game_plist: "respacked/game.plist",

    background: "res/backgrounds/background.jpg",
    level_bg1: "res/backgrounds/level_bg.jpg",
    level_bg2: "res/backgrounds/level_bg2.jpg",
    level_bg3: "res/backgrounds/level_bg3.jpg",

    pattern_bg: "res/backgrounds/pattern_bg_game.png",
    pattern_bg_hard: "res/backgrounds/pattern_bg_game_hard.png",

    words_full: "res/dictionary/ru_full.txt",
    words_popular: "res/dictionary/ru_popular.txt",

    letters_dict: {
        'а': 'a',
        'б': 'b',
        'в': 'v',
        'г': 'g',
        'д': 'd',
        'е': 'e',
        'ё': 'yo',
        'ж': 'zh',
        'з': 'z',
        'и': 'i',
        'й': 'j',
        'к': 'k',
        'л': 'l',
        'м': 'm',
        'н': 'n',
        'о': 'o',
        'п': 'p',
        'р': 'r',
        'с': 's',
        'т': 't',
        'у': 'u',
        'ф': 'f',
        'х': 'x',
        'ц': 'cz',
        'ч': 'ch',
        'ш': 'sh',
        'щ': 'shh',
        'ъ': 'tz',
        'ы': 'y',
        'ь': 'mz',
        'э': 'eh',
        'ю': 'yu',
        'я': 'ya'
    },

    cell: 'res/game/cell.png',
    board_bg: 'res/game/board_bg.png',
}
